### ISSUE TITLE
Solicitud de cooperación

### ISSUE THREAD

**Issue by SHIG-ops** [Stenfrank/dian-dv#1]
Hola,
Estamos trabajando en la implementación de la Factura Electrónica con un cliente colombiano y necesitamos ayuda para conectarnos con la DIAN, por lo que decidimos contactarlo con la esperanza de que nos pueda ayudar con su valiosa experiencia.
En este momento, nuestro equipo de desarrollo está trabajando en la solución, pero necesitamos a alguien que pueda ayudarnos a conectarnos con las autoridades tributarias colombianas (DIAN) al proporcionar entradas locales específicas. Esto tomaría aproximadamente 3-4 horas de su tiempo por semana, dependiendo de la fase de integración. 
Por supuesto, se le pagará por el tiempo invertido.

Háganos saber si está interesado en la cooperación para que podamos acordar los términos.

Gracias y saludos,
Sergio

**Comment by Stenfrank** [comment]
Hola @SHIG-ops me puedes indicar en que correo o numero nos podemos contactar o te puedes contactar directamente con nosotros  al correo info@soenac.com o al siguiente numero (57) 3193276206.

Quedamos atentos.

**Comment by Stenfrank** [comment]
Lo cierro cualquier cosa te puedes comunicar a los numero (032) 344-48-05 - (+57) 3193276206
